# Generated by Django 4.1.7 on 2023-03-14 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'ports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('slug', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('parent_slug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_slug', to='api.region')),
            ],
            options={
                'db_table': 'regions',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dest_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_prices', to='api.port')),
                ('orig_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_prices', to='api.port')),
            ],
            options={
                'db_table': 'prices',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='port',
            name='parent_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='api.region'),
        ),
    ]
