# Generated by Django 4.1.7 on 2023-03-14 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-day']},
        ),
        migrations.RenameField(
            model_name='price',
            old_name='date',
            new_name='day',
        ),
        migrations.AlterField(
            model_name='price',
            name='dest_code',
            field=models.ForeignKey(db_column='dest_code', on_delete=django.db.models.deletion.CASCADE, related_name='dest_prices', to='api.port'),
        ),
        migrations.AlterField(
            model_name='price',
            name='orig_code',
            field=models.ForeignKey(db_column='orig_code', on_delete=django.db.models.deletion.CASCADE, related_name='origin_prices', to='api.port'),
        ),
        migrations.AlterField(
            model_name='port',
            name='parent_slug',
            field=models.ForeignKey(db_column='parent_slug', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ports', to='api.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent_slug',
            field=models.ForeignKey(blank=True, db_column='parent_slug', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='child_slug',
                                    to='api.region'),
        ),
    ]
